const seederData = {
  1: [
    {
      id: 1,
      description: 'Lamborgini',
      category: 'Convertible',
      amount: '430',
      date: '01-02-2020',
    },
    {
      id: 2,
      description: 'Jaguar',
      category: 'Coupe',
      amount: '500',
      date: '01-06-2020',
    },
    {
      id: 3,
      description: 'Mercedes',
      category: 'Sedan',
      amount: '2030',
      date: '01-07-2020',
    },
    {
      id: 4,
      description: 'Lamborgini',
      category: 'Convertible',
      amount: '56000',
      date: '01-02-2020',
    },
    {
      id: 5,
      description: 'Jaguar',
      category: 'Sedan',
      amount: '500',
      date: '01-06-2020',
    },
    {
      id: 6,
      description: 'BMW',
      category: 'Sedan',
      amount: '2030',
      date: '01-07-2020',
    },
    {
      id: 7,
      description: 'Lamborgini',
      category: 'Convertible',
      amount: '56000',
      date: '01-02-2020',
    },
    {
      id: 8,
      description: 'Jaguar',
      category: 'Sedan',
      amount: '500',
      date: '01-06-2020',
    },
    {
      id: 10,
      description: 'BMW',
      category: 'Sedan',
      amount: '2030',
      date: '01-07-2020',
    },
    {
      id: 11,
      description: 'BMW',
      category: 'Sedan',
      amount: '2030',
      date: '01-07-2020',
    },
    {
      id: 12,
      description: 'BMW',
      category: 'Sedan',
      amount: '2030',
      date: '01-07-2020',
    },
    {
      id: 13,
      description: 'BMW',
      category: 'Sedan',
      amount: '2030',
      date: '01-07-2020',
    },
    {
      id: 14,
      description: 'BMW',
      category: 'Sedan',
      amount: '2030',
      date: '01-07-2020',
    },
    {
      id: 15,
      description: 'BMW',
      category: 'Sedan',
      amount: '2030',
      date: '01-07-2020',
    },
  ],
  2: [
    {
      id: 1,
      description: 'Tesla',
      category: 'Pickup Truck',
      amount: '430',
      date: '02-02-2020',
    },
    {
      id: 2,
      description: 'Tesla',
      category: 'SUV',
      amount: '500',
      date: '02-06-2020',
    },
    {
      id: 3,
      description: 'Honda',
      category: 'Sedan',
      amount: '2030',
      date: '02-07-2020',
    },
  ],
  3: [
    {
      id: 1,
      description: 'Ford',
      category: 'Pickup Truck',
      amount: '430',
      date: '03-02-2020',
    },
    {
      id: 2,
      description: 'Sample',
      category: 'Pickup Truck',
      amount: '500',
      date: '03-06-2020',
    },
    {
      id: 3,
      description: 'Tata',
      category: 'Hatchback',
      amount: '2030',
      date: '03-07-2020',
    },
  ],
  4: [
    {
      id: 1,
      description: 'Hyundai',
      category: 'Hatchback',
      amount: '430',
      date: '04-02-2020',
    },
    {
      id: 2,
      description: 'Volkswagen',
      category: 'Hatchback',
      amount: '500',
      date: '04-06-2020',
    },
    {
      id: 3,
      description: 'Tesla',
      category: 'Sedan',
      amount: '2030',
      date: '04-07-2020',
    },
  ],
  5: [
    {
      id: 1,
      description: 'Hyundai',
      category: 'Hatchback',
      amount: '430',
      date: '05-02-2020',
    },
    {
      id: 2,
      description: 'Volkswagen',
      category: 'Hatchback',
      amount: '500',
      date: '05-06-2020',
    },
    {
      id: 3,
      description: 'Tesla',
      category: 'Sedan',
      amount: '2030',
      date: '05-07-2020',
    },
  ],
  6: [
    {
      id: 1,
      description: 'Hyundai',
      category: 'Hatchback',
      amount: '430',
      date: '06-02-2020',
    },
    {
      id: 2,
      description: 'Volkswagen',
      category: 'Hatchback',
      amount: '500',
      date: '06-06-2020',
    },
    {
      id: 3,
      description: 'Tesla',
      category: 'Sedan',
      amount: '2030',
      date: '06-07-2020',
    },
  ],
  7: [
    {
      id: 1,
      description: 'Hyundai',
      category: 'Hatchback',
      amount: '430',
      date: '07-02-2020',
    },
    {
      id: 2,
      description: 'Volkswagen',
      category: 'Hatchback',
      amount: '500',
      date: '07-06-2020',
    },
    {
      id: 3,
      description: 'Tesla',
      category: 'Sedan',
      amount: '2030',
      date: '07-07-2020',
    },
  ],
  8: [
    {
      id: 1,
      description: 'Hyundai',
      category: 'Hatchback',
      amount: '430',
      date: '08-02-2020',
    },
    {
      id: 2,
      description: 'Volkswagen',
      category: 'Hatchback',
      amount: '500',
      date: '08-06-2020',
    },
    {
      id: 3,
      description: 'Tesla',
      category: 'Sedan',
      amount: '2030',
      date: '08-07-2020',
    },
  ],
  9: [
    {
      id: 1,
      description: 'Hyundai',
      category: 'Hatchback',
      amount: '430',
      date: '09-02-2020',
    },
    {
      id: 2,
      description: 'Volkswagen',
      category: 'Hatchback',
      amount: '500',
      date: '09-06-2020',
    },
    {
      id: 3,
      description: 'Tesla',
      category: 'Sedan',
      amount: '2030',
      date: '09-07-2020',
    },
  ],
  10: [
    {
      id: 1,
      description: 'Hyundai',
      category: 'Hatchback',
      amount: '430',
      date: '10-02-2020',
    },
    {
      id: 2,
      description: 'Volkswagen',
      category: 'Hatchback',
      amount: '500',
      date: '10-06-2020',
    },
    {
      id: 3,
      description: 'Tesla',
      category: 'Sedan',
      amount: '2030',
      date: '10-07-2020',
    },
  ],
  11: [
    {
      id: 1,
      description: 'Hyundai',
      category: 'Hatchback',
      amount: '430',
      date: '11-02-2020',
    },
    {
      id: 2,
      description: 'Volkswagen',
      category: 'Hatchback',
      amount: '500',
      date: '11-06-2020',
    },
    {
      id: 3,
      description: 'Tesla',
      category: 'Sedan',
      amount: '2030',
      date: '11-07-2020',
    },
  ],
  12: [
    {
      id: 1,
      description: 'Hyundai',
      category: 'Hatchback',
      amount: '430',
      date: '12-02-2020',
    },
    {
      id: 2,
      description: 'Volkswagen',
      category: 'Hatchback',
      amount: '500',
      date: '12-06-2020',
    },
    {
      id: 3,
      description: 'Tesla',
      category: 'Sedan',
      amount: '2030',
      date: '12-07-2020',
    },
  ],
};

export default seederData;
